feat: Add shape option to joystick
yoannmoinet/nipplejs pull request #107
Opened 2019-05-25 11:25 UTC by htshah

Feature add for issue #104.

2019-06-02 21:26 UTC, htshah commented
Changes done:
- [x] Reverted package-lock.json
- [x] Reverted all unrelated style changes

2020-03-19 16:58 UTC, darkworks commented
![button](https://user-images.githubusercontent.com/12841788/77093368-b110e080-6a2c-11ea-9af5-d065cf31c3b9.png)
![canvas](https://user-images.githubusercontent.com/12841788/77093377-b2420d80-6a2c-11ea-8c93-e812a2768bc5.png)

here is joystick shape , let see if we can add it

2020-08-10 14:48 UTC, Nek- commented
Hello guys. Any update on this? Should this work be finish? (it seems that only a rebase is required)

2020-08-15 12:32 UTC, htshah commented
@yoannmoinet 
Just a follow up for this PR, is there anything else on which you would like to comment?

2020-08-15 18:54 UTC, yoannmoinet commented
I'm off with no computer. 
It will have to wait next week end.
I'll add a reminder.

2020-08-24 14:06 UTC, yoannmoinet requested changes
Thank you for taking the time to implement this.
I have a few suggestions though.
Also, you're missing the types, you need to update [./types/index.d.ts](https://github.com/yoannmoinet/nipplejs/blob/master/types/index.d.ts) to add the new option.

2020-08-24 14:06 UTC, yoannmoinet commented on src/collection.js
> +    }
Although I think this process should be simplified.
Something like:

```javascript
/* utils.js */
export const clamp = (pos, min, max) => ({
    x: Math.min(Math.max(pos.x, min), max),
    y: Math.min(Math.max(pos.y, min), max)
});

/* collection.js */

// Clamp the position.
if (nipple.options.shape === 'circle') {
    dist = Math.min(dist, size);
    pos = u.findCoord(nipple.position, dist, angle);
} else {
    // Clamp to a square
    pos = u.clamp(nipple.position, -size, size);
    dist = u.distance(pos, nipple.position);
}

var xPosition = pos.x - nipple.position.x;
var yPosition = pos.y - nipple.position.y;

```

What do you think?

2020-08-30 11:25 UTC, htshah commented on src/nipple.js
> +    );
Made the necessary changes for this suggestion!

2020-08-30 11:53 UTC, htshah commented on src/collection.js
> +    }
@yoannmoinet 
Thank you for this great suggestion! I've implemented it but had to make some minor changes to the suggested `clamp()` function. Here's the updated function:
```js
/* utils.js */
// Clamp position within the range
export const clamp = (pos, nipplePos, size) => ({
    //                          left-clamping        right-clamping
    x: Math.min(Math.max(pos.x, nipplePos.x - size), nipplePos.x + size),
    //                          top-clamping         bottom-clamping
    y: Math.min(Math.max(pos.y, nipplePos.y - size), nipplePos.y + size)
});
```
Also, I've replaced switch statements with if-else statements as you requested.
Do let me know if there are any further changes required!

Thanks!

2020-09-06 21:48 UTC, yoannmoinet approved these changes
Well done, way simpler now.
LGTM.

2020-09-06 21:49 UTC, yoannmoinet commented
There are conflicts. 
Once they are fixed I'll merge the PR.

2020-09-06 21:49 UTC, yoannmoinet commented
NVM, I'll squash and merge.

2020-09-06 21:50 UTC, merged

2020-09-06 21:54 UTC, yoannmoinet commented
Published in `v0.8.6`

2020-09-07 05:17 UTC, htshah commented
Thank you soo much for accepting this PR. It is my first ever open source contribution.😁

2020-09-07 07:28 UTC, yoannmoinet commented
No problem @htshah that was a good contribution.
Well done, and thank YOU!