Add option to follow thumbstick when it reaches the border
yoannmoinet/nipplejs pull request #160
Opened 2021-02-18 13:05 UTC by emepetres

When follow option is set to true, the joystick follows the pointer when it reaches its border.

This is meant to improve usability on touch screens, when the user doesn't have the feedback of getting out the joystick zone.

2021-02-22 09:23 UTC, yoannmoinet commented
Hey thank you for this, I'll have a look.

2021-02-22 10:10 UTC, yoannmoinet requested changes
I've tested it, the movement is great and all, works exactly as expected.
Well done. (Even tested with the square shape, and it's working :100:)

But there seems to be an offset somewhere as soon as I reach the border of the back piece.
Not sure where it is coming from.

https://user-images.githubusercontent.com/597828/108692983-99c05a00-74fd-11eb-9ed9-007d767d45ea.mov

2021-02-22 10:10 UTC, yoannmoinet commented on README.md
> +Enable if the joystick must follow the thumbstick when it reaches the border.
That sounds weird, I know you wanted to follow the previous sentence, but I don't think it's working great in this context.

Maybe something like:

> Makes the joystick follow the thumbstick when it reaches the border.

WDYT?

2021-02-22 11:44 UTC, emepetres commented
Yep the offset is weird, in my project I set the zone to a specific div and it works as expected. Must be something css related, I'll take a look.

2021-02-22 15:26 UTC, yoannmoinet commented
It's probably the offset of the area to which the joystick is attached too.
If the area is top left, you won't have an offset I guess.

2021-02-24 14:11 UTC, yoannmoinet commented
@emepetres I have a fix, which also fixes other things I believe.
Do you mind if I commit in your branch?

2021-02-24 14:44 UTC, yoannmoinet commented
I want ahead and fixed it.
Thank you very much for this addition.
It will please and fix #13 😉

2021-02-24 14:45 UTC, yoannmoinet approved these changes

2021-02-24 14:46 UTC, merged

2021-02-24 15:58 UTC, matthewrobb commented
Thank you both!

2021-02-24 18:42 UTC, emepetres commented
sure thanks @yoannmoinet! I couldn't find time today to fix it, glad you did :)